version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - /usr/share/nginx/html:/usr/share/nginx/html:ro
    restart: unless-stopped
